CREATE TABLE condutores (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome VARCHAR(255) NOT NULL,
                            endereco_id BIGINT NOT NULL,
                            cpf VARCHAR(14) NOT NULL,
                            email VARCHAR(255) NOT NULL,
                            telefone VARCHAR(20) NOT NULL,
                            FOREIGN KEY (endereco_id) REFERENCES endereco(id)
);