CREATE TABLE parquimetro.endereco (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          logradouro VARCHAR(100),
                          numero INTEGER,
                          complemento VARCHAR(50),
                          cidade VARCHAR(50),
                          estado CHAR(2),
                          cep CHAR(8)
);