CREATE TABLE pagamentos (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            sessao_id BIGINT NOT NULL,
                            valor NUMERIC(10, 2) NOT NULL,
                            data_pagamento TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                            status_pagamento VARCHAR(50) NOT NULL,
                            FOREIGN KEY (sessao_id) REFERENCES sessao(id)
);