CREATE TABLE parquimetro (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             localizacao VARCHAR(255) NOT NULL,
                             status VARCHAR(50) NOT NULL,
                             capacidade_vagas INTEGER NOT NULL,
                             data_instalacao TIMESTAMP WITHOUT TIME ZONE NOT NULL
);