CREATE TABLE parquimetro.sessao (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        condutor_id BIGINT NOT NULL,
                        parquimetro_id BIGINT NOT NULL,
                        status_pagamento VARCHAR(50) NOT NULL,
                        inicio_sessao TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                        fim_sessao TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE sessao
    ADD CONSTRAINT fk_condutor
        FOREIGN KEY (condutor_id)
            REFERENCES condutores(id);

ALTER TABLE sessao
    ADD CONSTRAINT fk_parquimetro
        FOREIGN KEY (parquimetro_id)
            REFERENCES parquimetro(id);
