CREATE TABLE veiculos (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          placa VARCHAR(20) NOT NULL,
                          modelo VARCHAR(100),
                          marca VARCHAR(100),
                          condutor_id BIGINT,
                          FOREIGN KEY (condutor_id) REFERENCES condutores(id)
);
